version: '2.4'

services:
  shhgit-www:
    build: ./www
    container_name: shhgit.www
    ports:
      - 8080:80 # if you change your local port, public/script.js:1273
    volumes:
      - ./www/public:/usr/share/nginx/html:ro

  shhgit-app:
    build: ./
    container_name: shhgit.app
    entrypoint: ["/app/shhgit"]
    depends_on:
      - shhgit-www
    volumes:
      - ./config.yaml:/app/config.yaml:ro